### ISSUE TITLE
error 379

### ISSUE THREAD

**Issue by imsachaves** [forestbiotech-lab/sRNA-workflow#17]
I am trying to rerun miRPursuit with a customize miRBase but I am having this problem:

 ./miRPursuit.sh -f 119 -l 127 --fastq --trimm  hvfastq-
not git
Update check disabled
Java set up: OK
Workbench set up OK
:: Running pipeline with the following arguments:
First Library			= 119
Last Library			= 127
Number of threads		= 20
Filter suffix               = 18_26_5
Genome                      = /home/ichaves/source_data/cafe/Hv_genome_2019/GCA_004125335.1_ASM412533v1_genomic.fna
Genome mircat               = /home/ichaves/source_data/cafe/Hv_genome_2019/GCA_004125335.1_ASM412533v1_genomic.fna
miRBase                     = /home/ichaves/source_data/mirbase/mir_rfam.fa
Working directory (workdir) = /home/ichaves/miRPursuit_Projects/Hemileia_miRBasev22_Hv_genome_2019_rfam/
sRNA directory (INSERTS_DIR)= /home/ichaves/smallRNAHemileia/fastq/
First lib to be processed   = hvfastq-119.fq
==> Attention!
workdir - /home/ichaves/miRPursuit_Projects/Hemileia_miRBasev22_Hv_genome_2019_rfam/ 
Data already that exists in this folder might be overwritten.
Continue? (Y/N)y

==> Running in fastq mode. - Copying fastq files...
==> Error on line 379 caused a code 1 exit - miRPursuit.sh
Try using a different sequence of libraries or try a new pattern to select libraries.

**Comment by BrunoEVCosta** [comment]
Hello @imsachaves  the pattern cannot have a space, or else it will be considered a new command.
```--trimm hvfastq-```
Possible confusion --fastq requires an argument while --trim  is only a flag.
either use hvfastq- as the pattern or rename all file to remove all spaces
